### ISSUE TITLE
Улучшить стабильность связки esp8266 и dht22

### ISSUE THREAD

**Issue by sergey-light** [KirinDenis/owlos#16]
В настоящее время есть сабжевая связка, периодически наблюдаю что в сети устройствое есть, пингуется, а по http данные не отдает. 
На данный момент прицепил через usb к компу смотрю что в консоли

**Comment by KirinDenis** [comment]
Влияние оказывает качество самого сенсора и его соединения с конроллером. Необходимо внимательно наблюдать за временем отклика сенсора.
