### ISSUE TITLE
ESP32 - Разборка распиновки

### ISSUE THREAD

**Issue by Nhungyy** [KirinDenis/owlos#30]

**Comment by KirinDenis** [comment]
Необходимо собрать несколько различных схем, проверить их работоспособность с ESP32 (поэксперенетировать с различными пинами)

**Comment by KirinDenis** [comment]
Много изменений для WebUX и OWLOS связаных с управлением пинами и вообще свойствами драйверов. 
WebUX исправил куча мелочей связаных с отвером от RESTful относительно изменения свойств драйверов
(возвращение ошибок). 
Протестировал пока на ActuatorDriver для цифровых и аналоговых пинов (с учетом PWM).

Дельше начну тестировать сенсоры. 

Ветка:
**fix/Issues_30_ESP32_PINs**

**Comment by KirinDenis** [comment]
Закончено, протестировано с различными драйверами
